version: "3.9"  # optional since v1.27.0
services:
  puppet:
    build:
      dockerfile: puppet/Dockerfile.puppet
    links:
      - browserless
    environment:
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3000
      - DEBUG="*"
    depends_on:
      - "browserless"
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    command: "./run-forever.sh 12h ./run.sh"
    volumes:
      - "./data:/app/data:z"

  browserless:
    image: docker.io/browserless/chrome
    environment:
      - PREBOOT_CHROME=true
      - MAX_CONCURRENT_SESSIONS=1
      - KEEP_ALIVE=1
      - CONNECTION_TIMEOUT=60000

  git:
    build:
      dockerfile: puppet/Dockerfile.git
    environment:
      GIT_AUTHOR_NAME: "O.D.I.A. Automaton"
      GIT_AUTHOR_EMAIL: "bot@odia.legal"
    command: "./run-forever.sh 12h 'cd data && git add * && git commit -asm \"autocommit $(date)\"'"
    depends_on:
      - "puppet"
    volumes:
      - "./data:/app/data:z"

  bot:
    build:
      dockerfile: telegram/Dockerfile
    env: telegram/.env
    depends_on:
      - "puppet"
    volumes:
      - "./data:/app/data:z"
