version: "3.9"  # optional since v1.27.0
environment:
  RUN_TIME: "1h"
services:
  puppet:
    build:
      dockerfile: Dockerfile.puppet
      context: puppet
    links:
      - browserless
    environment:
      BROWSERLESS_HOST: browserless
      BROWSERLESS_PORT: 3000
      DEBUG: "puppet"
    depends_on:
      - "browserless"
    command: "./run-forever.sh 1h ./run.sh"
    volumes:
      - "./data:/data:z"

  browserless:
     image: docker.io/zenika/alpine-chrome
     entrypoint: ["sh", "-c", "while true; do chromium-browser --headless --use-gl=swiftshader --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=3000; sleep 2; done"]
     port:
       - "3000:3000"

  git:
    build:
      dockerfile: Dockerfile.git
      context: puppet
    environment:
      GIT_AUTHOR_NAME: "O.D.I.A. Automaton"
      GIT_AUTHOR_EMAIL: "bot@odia.legal"
    command: "./run-forever.sh 1h 'cd /data && git add . && git commit -asm \"autocommit \"'"
    depends_on:
      - "puppet"
    volumes:
      - "./data:/data:z"

  bot:
    build:
      context: telegram
    env_file: telegram/.env
    depends_on:
      - "puppet"
    volumes:
      - "./data:/data:z"
