version: "3.9"  # optional since v1.27.0
services:
  puppet:
    build: .
    links:
      - browserless
    environment:
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3000
      - DEBUG=puppet
    depends_on:
      - "browserless"
    command: "./run.sh"
    volumes:
      - "./data:/app/data"

  browserless:
    image: chrome
