FROM alpine:latest as build
MAINTAINER Niv Sardi <x@filtra.me>
WORKDIR /app

RUN apk add git
COPY run-forever.sh ./
RUN chmod +x run-forever.sh

CMD ./run-forever.sh 12h 'git add * && git commit -asm "autocommit $(date)"'
