FROM node:alpine as build
MAINTAINER Niv Sardi <x@filtra.me>
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY package.json tsconfig.json ./
RUN npm install

COPY src ./src
COPY run.sh run-forever.sh ./
RUN chmod +x run.sh run-forever.sh

CMD ./run.sh
